source 'https://rubygems.org'

gem 'capybara'
gem 'capybara-screenshot'
gem 'cucumber'
gem 'faker'
gem 'ostruct'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-checkstyle_formatter'
gem 'site_prism'
